spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kleider_shop
    username: root
    password:
    testOnBorrow: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDBDialect

  jackson:
    serialization:
      write_dates_as_timestamps: false

jwt:
  secret: secret

password:
  secret: secret

tomcat:
  ajp:
    enabled: false

server:
  port: 3000
