spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kleider_shop
    username: root
    password:
    testOnBorrow: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none