spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kleider_shop
    username: root
    password:
    testOnBorrow: true
  jpa:
    hibernate:.ddl-auto: update
    generate-ddl: true
    show-sql: true

  jackson:
      serialization:
        write_dates_as_timestamps: false